### ISSUE TITLE
[Feature Request] add no watermark function to video

### ISSUE THREAD

**Issue by Tianqi-Dotes** [Russell-Newton/TikTokPy#28] opened 2023-01-26 12:45 UTC
case:

video url: 
https://www.tiktok.com/@skynews/video/7192867272225000710

watermark url:
https://v16m-default.akamaized.net/b7b2ea9125bb68666109897fa7215709/63d2c761/video/tos/useast2a/tos-useast2a-pve-0068/oUIAhfg2Q9LtDB6owxVHAqkSOjICUEgUzRUSho/?a=0&ch=0&cr=0&dr=0&lr=all&cd=0%7C0%7C0%7C0&cv=1&br=1260&bt=630&cs=0&ds=3&ft=XE5bCqT0mv_PD12~CrTq3wUjZ.9VMeF~OD&mime_type=video_mp4&qs=0&rc=NDk0OmY0PDg2Zzk7OTY8O0BpM2xsaTQ6Zjg2aTMzNzczM0A2NDU2Y14uNTUxYzQzXzQ1YSNpLV5ocjRvLjZgLS1kMTZzcw%3D%3D&l=20230126123208C632DE2B1997DC337123&btag=80000

no watermark url:
https://v16m-default.akamaized.net/492d9274c60b431520dcf7123a96fc58/63d2c761/video/tos/useast2a/tos-useast2a-ve-0068c001/oUgUoG6IoUuMgXxq9fRLC7hDSzBstWASIQAh3k/?a=0&ch=0&cr=0&dr=0&lr=all&cd=0%7C0%7C0%7C0&cv=1&br=1108&bt=554&cs=0&ds=6&ft=XE5bCqT0mv_PD12~CrTq3wUjZ.9VMeF~OD&mime_type=video_mp4&qs=0&rc=OWc6ZzY4OjQ0PDM6NmQ6OkBpM2xsaTQ6Zjg2aTMzNzczM0AuYjYuXjEwNV8xNS0zLTVjYSNpLV5ocjRvLjZgLS1kMTZzcw%3D%3D&l=20230126123208C632DE2B1997DC337123&btag=80000

functions reference:
https://github.com/Evil0ctal/Douyin_TikTok_Download_API
API try here:
https://api.tikhub.io/docs
https://api.tikhub.io/docs#/TikTok/tiktok_video_data_tiktok_video_data__get
the route : /tiktok_video_data
noted: api in https://api.tikhub.io/docs is v3.2.9 which is not opensource, the `https://github.com/Evil0ctal/Douyin_TikTok_Download_API` is opensource and the version is 3.1.2, this version has the no wartermark function.

**Comment by Russell-Newton** [comment] 2023-01-30 05:46
Duplicate of #3. I will not be implementing this feature, but contributors are welcome to fork and open a PR if someone else wants to do this.

**Closed by Russell-Newton** 2023-01-30 05:46 UTC
Labels: duplicate
