### ISSUE TITLE
Unable to fetch video comments

### ISSUE THREAD

**Issue by RenHong-HC** [Russell-Newton/TikTokPy#41] opened 2023-05-18 08:43 UTC
I want to get the comments of the video, but the data obtained by the following code is empty

```
from tiktokapipy.api import TikTokAPI
def do_something():
    with TikTokAPI(navigator_type = 'chromium') as api:
        video = api.video("https://www.tiktok.com/@sstowen/video/7232788728538844459")
        comments = video.comments
        comment_text = [comment.text for comment in comments]
        print("Comments: ", comment_text)

do_something()
```
console print result

```
A second attempt might work.
  video = api.video("https://www.tiktok.com/@sstowen/video/7232788728538844459")
Comments:  []
```
I checked the related issues, but I didn't find a suitable answer, I hope to get your help

**Comment by Russell-Newton** [comment] 2023-05-18 12:13
Duplicate of #23, #30. I'm planning on working on this issue this week and next. Please follow one of those issues to get updates about collecting comments. I'm closing this as a duplicate.

**Closed by Russell-Newton** 2023-05-18 12:13 UTC
Labels: duplicate, question

**Comment by RenHong-HC** [comment] 2023-05-24 12:20
ok, thanks for your reply!
